Here is my homeworks: 1, 2, 3, 4
Denys320/goit-markup-hw-03 pull request #1
Opened 2023-01-07 21:20 UTC by Denys320

2023-01-27 22:30 UTC, xrustic2020 commented
Обрати внимание на имя файла - "images/envelope _hover.svg"

Переключись на текущую ветку  "my-homeworks-1-2-3-4", внеси правки, потом закомить и запуш изменения

2023-01-27 22:32 UTC, xrustic2020 commented
"images/typing on keyboard.jpg" - подумай что тут не так с именем файла?)

2023-01-27 22:48 UTC, xrustic2020 commented
1 домашка:
- «A3» У назвах файлів відсутні великі літери, пробіли і трансліт, тільки літери і слова англійської мови. 

Пересмотри, плиз имена файлов, особенно картинок. Старайся придерживаться одного стиля в именах файлов, назвать файл group_team_photo.jpg или group-team-photo.jpg - тут решать тебе. Если выбрал писать имена через - (тире) то старайся везде в проекте через тире имена делать, если выбрал через _(нижний) то так и во всех файлах

2023-01-28 11:13 UTC, xrustic2020 commented
признавайся проганял растровые изображения через squoosh ?)

2023-01-28 13:10 UTC, xrustics requested changes

2023-01-28 13:10 UTC, xrustics commented on index.html
> +                Ідейні міркування, i навіть початок<br />
старайся избегать использования тега br
лучше - ограничь блок с текстом по ширине и текст сам перенесется)

2023-01-28 13:10 UTC, xrustics commented on index.html
> +              <h4 class="title">УВАГА ДО ДЕТАЛЕЙ</h4>
используй заголовки не по тому какие для них базовые стили а по очереди. Т.е. по структуре сначала h1 потом h2 потом уже h3 и потом аж h4
Это важный момент для анализаторов поисковых систем и для читалок (для людей с ограниченными возможностями)
у тебя на строке 64 идет "h2" ( class="hero-title") а тут уже сразу  h4 (пропустил h3 по структуре документа)
Представляй тут все как в газете, от большего заголовка к меньшему (по очереди)

2023-01-28 13:10 UTC, xrustics commented on index.html
> +              <h4 class="title">УВАГА ДО ДЕТАЛЕЙ</h4>
а стили оставь для CSS)

2023-01-28 13:10 UTC, xrustics commented on index.html
> +              <h4 class="title">УВАГА ДО ДЕТАЛЕЙ</h4>
скрин из валидатора:
<img width="1142" alt="image" src="https://user-images.githubusercontent.com/59570719/215223277-504e631c-0b9f-43ef-893b-df98230f16ed.png">

2023-01-28 13:10 UTC, xrustics commented on css/styles.css
> +  margin-right: auto;
вместо двух правил (margin-left: auto;
  margin-right: auto;), чтобы центрировать контент можно используй одним правилом - margin: 0 auto; (по факту это то же самое)

2023-01-28 13:10 UTC, xrustics commented on css/styles.css
> +  padding-right: 15px;
тут аналогично вместо двух правил padding-left: 15px;
  padding-right: 15px; используй одно правило padding: 0px 15px;
можно детальнее почитать тут: https://developer.mozilla.org/ru/docs/Web/CSS/padding#%D1%81%D0%B8%D0%BD%D1%82%D0%B0%D0%BA%D1%81%D0%B8%D1%81

2023-01-28 13:10 UTC, xrustics commented on index.html
> +          <li class="logo-footer">
это не список
список это набор однотипных єлементов, а в этом месте элементы далеко не похожи друг на друга, по крайней мере лого точно не относится к этому списку)

2023-01-28 13:10 UTC, xrustics commented on index.html
> +          <li class="logo-footer">
вынеси лого из ul списка

2023-01-28 13:10 UTC, xrustics commented on index.html
> +          <a href="index.html" class="logo">
тегу ссылки "а" - не нужен целый класс logo, т.к. в logo целый набор неиспользуемых правил. А по факту тегу ссылки "а" нужно только правило text-decoration: none;

лучше создай отдельный класс только с одним правилом text-decoration: none;

2023-01-28 13:10 UTC, xrustics commented on css/styles.css
> +  color: var(--accent-color);
а зачем тут настолько специфичное правило?
по факту используется класс current только в одном месте
достаточно просто .current {...

2023-01-28 13:10 UTC, xrustics commented on index.html
> +              <a href="./index.html" class="link current">Студія</a>
класс current тебе не понадобится совсем) в макете окрашено в синий цвет для того чтоб продемонстрировать hover єфект. Т.е. изначально она не должна біть синей

2023-01-28 13:10 UTC, xrustics commented on index.html
> +            <li class="item tel">
не нашел в css файле класса tel
проверь нужен ли он тут

2023-01-28 13:10 UTC, xrustics commented on index.html
> +        <button class="button primary" type="button">Замовити послугу</button>
не нашел в css файле класса primary
проверь нужен ли он тут

2023-01-28 13:10 UTC, xrustics commented on css/styles.css
> +.clients-list .icon-yaco {
зачем такая специфичность для icon-yaco ?
оно используется только в одном месте в html файле

2023-01-28 13:10 UTC, xrustics commented on css/styles.css
> +.clients-list .icon-yaco {
аналогично и длч .icon-companytag и icon-limecompany, .icon-foster и другие доп классі єтого же списка

2023-01-28 13:10 UTC, xrustics commented on index.html
> +                ><svg class="auth-icon" width="10" height="16">
старайся использовать целіе числа для атрибутов и стилей width  height padding и т.д.
если в макете число с точкой - округляй
єто фактически неточности макета...

2023-01-28 13:10 UTC, xrustics commented on index.html
> +            <a class="logo footer" href="index.html">Web<span>Studio</span></a>
тут не нужен класс footer
ті об.явил класс footer (задает фон) для всего блока, доваблять отдельно для елементов уже не нужно, єто уже будет дубляжем

2023-01-28 13:10 UTC, xrustics commented on index.html
> +          <li class="footer nav">
не нашел в css файле класса nav
проверь нужен ли он тут

2023-01-28 14:49 UTC, xrustic2020 commented
По домашке 2
«B12» Розмітка хедера і футера однакова на всіх сторінках. - проверь єтот пункт для index та portfolio

2023-01-28 14:51 UTC, xrustic2020 commented
2 домашка
«С5» Текст контактів в хедері і футері змінює колір при ховері і фокусі. - єтого функционала не увидел)

2023-01-28 14:53 UTC, xrustic2020 commented
2 домашка
«С9» Сімейство шрифтів Roboto явно задане тільки для елемента <body>, інші елементи наслідують його.
увидел что Roboto обьявлен в нескльких правилах css) пересмотри плиз

2023-01-28 14:54 UTC, xrustic2020 commented
2 домашка
«С10» Для елемента <body> задана властивість color з кольором тексту, домінантним на макеті. Решта тексту наслідує або перекриває це значення 
проверь и єтот момент тоже)

2023-01-28 14:56 UTC, xrustic2020 commented
2 домашка
«С15» Вага шрифту (властивість font-weight) явно вказана тільки, якщо значення в макеті відрізняється від стандартного для цього елемента в браузері.
обрати внимание и пересмотри стили где излишне употребляется єто правило

2023-01-28 14:57 UTC, xrustic2020 commented
2 домашка
«С16» Кнопкам задана властивість cursor зі значенням pointer.
особенно для файла portfolio просмотри

2023-01-28 14:58 UTC, xrustic2020 commented
по 2 домашке
«С17» У стилях не повторюються значення властивостей, які задані браузером за замовчуванням. Наприклад, посиланням не потрібно вказувати cursor: pointer, а абзацам font-style: normal або font-weight: 400.
проверь)

2023-01-28 14:58 UTC, xrustic2020 commented on index.html
> +            <a class="footer-adr" href="#">м. Київ, пр-т Лесі Українки, 26</a>
не хватает тега address 
«B16» Тег <address використаний тільки у футері.

2023-01-28 14:58 UTC, xrustic2020 commented on index.html
> +            <a class="footer-adr" href="#">м. Київ, пр-т Лесі Українки, 26</a>
https://www.edu.goit.global/uk/learn/8046784/845990/845996/textbook

2023-01-28 14:58 UTC, xrustic2020 commented on portfolio.html
> +          <a href="index.html" class="logo">
проверь плиз отображение лого
мне кажется что размерчик не по макету)
<img width="1430" alt="image" src="https://user-images.githubusercontent.com/59570719/215271842-abf0d903-080d-4a21-bc9d-712e75ac2217.png">

2023-01-28 14:58 UTC, xrustic2020 commented on portfolio.html
> +          <li class="radio-button"><button type="button">Усі</button></li>
попробуй использовать для правил css такой селектор .radio li {...
єто будет проще и тогда можно будет убрать класс radio-button со всех li)

2023-01-28 14:58 UTC, xrustic2020 commented on portfolio.html
> +            <li class="product-card">
тут тоже избався от классов для li, так будет чище
подскказочка для селектора -  .product li { ...

2023-01-28 14:58 UTC, xrustic2020 commented on portfolio.html
> +            <a class="logo footer" href="index.html">Web<span>Studio</span></a>
лого - єто не єлемент списка, так что виноси его из списка)

2023-01-28 14:58 UTC, xrustic2020 commented on portfolio.html
> +          <li class="footer nav">
избавься от классов у li аналогично)

2023-01-28 14:58 UTC, xrustic2020 commented on portfolio.html
> +          <h4>приєднуйтесь</h4>
а вот тут иконки - єто список)

2023-01-28 14:58 UTC, xrustic2020 commented on portfolio.html
> +            <a class="footer-adr" href="#">м. Київ, пр-т Лесі Українки, 26</a>
тут должно обернуто в address

2023-01-28 14:58 UTC, xrustic2020 commented on index.html
> +            <li class="item tel">
уже нашел, но проверь те ненужние специфичности

2023-01-28 14:58 UTC, xrustic2020 commented on index.html
> +        <button class="button primary" type="button">Замовити послугу</button>
уже нашел но пофикси со специфичностью

2023-01-28 14:58 UTC, xrustic2020 commented on index.html
> +          <li class="footer nav">
нашел но нужно исправить селектори со ненужной специфичностью

2023-01-28 23:05 UTC, Denys320 commented
> По домашке 2 «B12» Розмітка хедера і футера однакова на всіх сторінках. - проверь єтот пункт для index та portfolio

все проверил

2023-01-29 08:20 UTC, Denys320 commented
> 2 домашка «С5» Текст контактів в хедері і футері змінює колір при ховері і фокусі. - єтого функционала не увидел)

поправил

2023-01-29 08:26 UTC, Denys320 commented
> 2 домашка «С9» Сімейство шрифтів Roboto явно задане тільки для елемента , інші елементи наслідують його. увидел что Roboto обьявлен в нескльких правилах css) пересмотри плиз

есть)

2023-01-29 08:48 UTC, Denys320 commented
> 2 домашка «С10» Для елемента задана властивість color з кольором тексту, домінантним на макеті. Решта тексту наслідує або перекриває це значення проверь и єтот момент тоже)

done)

2023-01-29 08:52 UTC, Denys320 commented
> 2 домашка «С15» Вага шрифту (властивість font-weight) явно вказана тільки, якщо значення в макеті відрізняється від стандартного для цього елемента в браузері. обрати внимание и пересмотри стили где излишне употребляется єто правило

есть, лишнее поудалял

2023-01-29 08:54 UTC, Denys320 commented
> 2 домашка «С16» Кнопкам задана властивість cursor зі значенням pointer. особенно для файла portfolio просмотри

это тоже есть, везде где кнопка курсор меняется

2023-01-29 08:59 UTC, Denys320 commented
> по 2 домашке «С17» У стилях не повторюються значення властивостей, які задані браузером за замовчуванням. Наприклад, посиланням не потрібно вказувати cursor: pointer, а абзацам font-style: normal або font-weight: 400. проверь)

тоже пересмотрел, все нормально вроде) блин)) я печатаю по памяти, все буквы у меня английские

2023-01-29 18:27 UTC, xrustic2020 approved these changes

2023-01-29 18:27 UTC, xrustic2020 commented on css/styles.css
>  .clients-list .icon-tagline {
Отличное решение!

2023-01-29 18:29 UTC, xrustic2020 commented
все отлично, молодец) 
Модуль 1 и 2 - DONE))

2023-02-08 20:58 UTC, xrustic2020 commented
3 домашка
«B13» У хедера є нижня рамка, необхідно сильно наблизити макет, щоб побачити її.
проверь, т.к. я пока не увилел реализации)

2023-02-09 08:24 UTC, xrustic2020 commented
3 домашка
«B15» Для всіх секцій використовується один клас .section, задані верхні і нижні падінги по 94px, що відсувають контент всередину секції.

проверь, плиз, бо такого класса и реализации я у тебя не нашел

2023-02-09 08:29 UTC, xrustic2020 commented
3 домашка
«B17» У картках на сторінці Портфоліо є рамка (властивість border), але тільки у нижній частині картки.
у тебя не нашел такого, добавь, плиз) Скрин с макета:
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/59570719/217757617-cc88abdc-3d75-4533-9edd-390c991e92c1.png">

2023-02-09 08:40 UTC, xrustic2020 commented
пересмотри плиз внимательно видос по сеткам - https://drive.google.com/file/d/1mQW8d7rKEsReSolvmg-kIhsIiiTtFx5x/view
и примени тут

Єто из 3 домашки 
«B16» Для побудови сіток використовується техніка, що описана у конспекті і відео-майстерні.

2023-02-09 09:04 UTC, xrustics commented
По 4 домашке только єто пофиксить и все)
«A2» Усі векторні зображення (іконки) зібрані в SVG-спрайт icons.svg, який лежить у папці images.
исправь плиз как в задании (переименуй файл и поправь импорт у всех)

2023-02-09 09:14 UTC, xrustic2020 commented
И еще посмотри вот на єтот момент: 
![image](https://user-images.githubusercontent.com/59570719/217768501-074b86c4-d287-47aa-b99e-b25c9c6894c6.png)

Постарайся сам разобраться почему так случилось и исправь) Иконка не должна вілазить за рамки своего родителя

2023-02-09 09:51 UTC, xrustic2020 commented
Такого отступа не должно біть, попробуй сам ответить на вопрос в чем причина)
Если не будет идей - обращайся, подскажу как пофиксить
![image](https://user-images.githubusercontent.com/59570719/217778035-2aa1dd52-6bcb-4dc4-957b-fafb7763b9e2.png)

2023-02-09 13:18 UTC, xrustics commented
> пересмотри плиз внимательно видос по сеткам - https://drive.google.com/file/d/1mQW8d7rKEsReSolvmg-kIhsIiiTtFx5x/view и примени тут
> 
> Єто из 3 домашки «B16» Для побудови сіток використовується техніка, що описана у конспекті і відео-майстерні.

- тут перепроверил, у тебя все ок) отбой))

2023-02-09 13:24 UTC, xrustics commented on index.html
>                <img
(домашка 3)
проверь вот этот отступ, его не должно быть:
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/59570719/217646270-8e59fc07-d4a9-40d5-b06e-e2dc1a1c5053.png">

2023-02-09 13:24 UTC, xrustics commented on index.html
> -            <li class="item">
(домашка 3) проверь єто условие - "«B5» Для проміжку між межею батька і його дитиною використовується властивість padding."
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/59570719/217648488-ecfcadc0-8049-4c49-868c-614b38736417.png">

2023-02-11 14:38 UTC, Denys320 commented
> 3 домашка «B13» У хедера є нижня рамка, необхідно сильно наблизити макет, щоб побачити її. проверь, т.к. я пока не увилел реализации)

done!

2023-02-11 14:43 UTC, Denys320 commented
> 3 домашка «B15» Для всіх секцій використовується один клас .section, задані верхні і нижні падінги по 94px, що відсувають контент всередину секції.
> 
> проверь, плиз, бо такого класса и реализации я у тебя не нашел

у меня там применен падинг, но немного не так как написано, применен на другие теги или классы, но если надо переделать, то я переделаю)

2023-02-12 12:36 UTC, Denys320 commented
> И еще посмотри вот на єтот момент: ![image](https://user-images.githubusercontent.com/59570719/217768501-074b86c4-d287-47aa-b99e-b25c9c6894c6.png)
> 
> Постарайся сам разобраться почему так случилось и исправь) Иконка не должна вілазить за рамки своего родителя

done) добавил на svg размеры, у меня это вроде в следующих домашках уже исправлено)

2023-02-12 13:00 UTC, Denys320 commented
> Такого отступа не должно біть (от картинки до границ li-шки), попробуй сам ответить на вопрос в чем причина) Если не будет идей - обращайся, подскажу как пофиксить маленькая подсказка - https://textbook.edu.goit.global/html-css-a7u5xv/v1/uk/docs/lesson-05/box-types/#%D0%BF%D1%80%D0%BE%D0%BC%D1%96%D0%B6%D0%BE%D0%BA-%D1%83-%D1%80%D1%8F%D0%B4%D0%BA%D0%BE%D0%B2%D0%B8%D1%85-%D0%B5%D0%BB%D0%B5%D0%BC%D0%B5%D0%BD%D1%82%D1%96%D0%B2 ![image](https://user-images.githubusercontent.com/59570719/217778035-2aa1dd52-6bcb-4dc4-957b-fafb7763b9e2.png)

done

2023-02-12 13:07 UTC, Denys320 commented
> По 4 домашке только єто пофиксить и все) «A2» Усі векторні зображення (іконки) зібрані в SVG-спрайт icons.svg, який лежить у папці images. исправь плиз как в задании (переименуй файл и поправь импорт у всех)

done)

2023-02-12 13:42 UTC, Denys320 commented
> 3 домашка «B17» У картках на сторінці Портфоліо є рамка (властивість border), але тільки у нижній частині картки. у тебя не нашел такого, добавь, плиз) Скрин с макета: <img alt="image" width="1440" src="https://user-images.githubusercontent.com/59570719/217757617-cc88abdc-3d75-4533-9edd-390c991e92c1.png">

done!!)

2023-02-12 23:11 UTC, xrustic2020 commented
В целом все ок) 
3 и 4 домашки я тоже готов принять у тебя, но после небольшого созвона и livecoding)
будет пару вопросов и небольшой хот фикс во время созвона)

2023-02-13 16:20 UTC, merged