my-new-hw5
Denys320/goit-markup-hw-03 pull request #2
Opened 2023-02-14 13:38 UTC by Denys320

моя 5-я домашка

2023-02-14 14:28 UTC, xrustic2020 commented on index.html
> +
backdrop обычно должен быть внутри main
Есть ли требование для модалки чтоб єтот кусочек вне main был?

2023-02-14 14:35 UTC, xrustic2020 commented on css/styles.css
> +  bottom: 4px;
кажется єтот костыль с 4px тут больше не нужен)
![image](https://user-images.githubusercontent.com/59570719/218768768-8175b5f4-c37c-4871-97a9-6ca72a6df23c.png)

2023-02-14 14:54 UTC, xrustic2020 commented
.product li p {
  font-size: 16px;
  line-height: 1.88;
  letter-spacing: 0.03em;
  margin-bottom: 0;
  margin-top: 4px;
}

кажется тут margin-top: 4px; излишний
проверь поведение єтой виезжалки с синим бекдропом, она как будто скачет немножко когда доезжает до конца (обрати внимание на нижнюю границу)

2023-02-14 15:00 UTC, xrustic2020 commented
Нужно пофиксить центрирование по вертикали для елментом хедера + декоративная синяя линия
<img width="1440" alt="Знімок екрана 2023-02-14 о 16 57 32" src="https://user-images.githubusercontent.com/59570719/218775315-f2480d88-a624-4d4e-9ecc-48dae288ea4f.png">

2023-02-14 15:12 UTC, xrustic2020 commented
Зафикси єтот момент, так не должно біть
![image](https://user-images.githubusercontent.com/59570719/218778464-061689f0-197c-49d3-9bd1-3e7fd8be357d.png)

2023-02-14 15:16 UTC, xrustic2020 requested changes

2023-02-14 15:16 UTC, xrustics commented on css/styles.css
> +  bottom: 4px;
"width: 370px" замени на "left: 0, right: 0"
єто надежнее, т.к. ти не будешь привязиваться к какому то статическому значению ширини. "left: 0, right: 0" - єто всегда будет заполнять блок полностью до краев (левого и правого)

Єто еще и легче будет поддерживать) например заказчик захочет изменить размер карточек - если использовать width то тебе прийдется для всех карточек менять width + еще и размер width для каждого бейджика с оверлеем менять) а если ти используешь "left: 0, right: 0" - то для изменения размера карточки нужно будет поменять только размер карточки)) а тот бейдж с оверлеем сам подстроиться)

2023-02-14 15:16 UTC, xrustics commented on index.html
>                  alt="watching to the tablet"
кажется ошибка в имени файла 
<img width="1440" alt="Знімок екрана 2023-02-14 о 16 42 12" src="https://user-images.githubusercontent.com/59570719/218770777-e761295d-1751-4308-85d3-fb6be9d12dc8.png">

2023-02-14 15:16 UTC, xrustics commented on portfolio.html
> +              <div class="product-thumb">
кажется тут размери и отступи посьезжали
<img width="1440" alt="Знімок екрана 2023-02-14 о 16 50 21" src="https://user-images.githubusercontent.com/59570719/218774370-4799d036-10ab-41c4-a298-83db623425cd.png">

2023-02-14 15:16 UTC, xrustics commented on css/styles.css
> +  background: rgba(0, 0, 0, 0.2);
тут ошибка синтаксиса "animation-name: ;"

2023-02-14 15:19 UTC, xrustic2020 commented
<img width="1440" alt="Знімок екрана 2023-02-14 о 16 34 28" src="https://user-images.githubusercontent.com/59570719/218780198-f2e516e7-de51-400c-b752-f29df9ddb738.png">

2023-02-15 17:25 UTC, Denys320 commented on index.html
> +
fixed)

2023-02-15 17:28 UTC, Denys320 commented on css/styles.css
> +  bottom: 4px;
fixed) да, очень крутой совет)

2023-02-15 17:50 UTC, Denys320 commented
> 
я проверил и этот маржин нужет по макету, а выезжалка скачет изза другой какой то причины, и я такого почему то не видел, щас буду искать что там и почему)

2023-02-15 17:56 UTC, Denys320 commented
> Нужно пофиксить центрирование по вертикали для елементов хедера + декоративная синяя линия и пересмотри плиз центрирование иконок относительно их текста (типа телефон со своей иконкой должні біть на одном уровне) <img alt="Знімок екрана 2023-02-14 о 16 57 32" width="1440" src="https://user-images.githubusercontent.com/59570719/218775315-f2480d88-a624-4d4e-9ecc-48dae288ea4f.png">

fixed)

2023-02-15 18:19 UTC, Denys320 commented
> Зафикси єтот момент, так не должно біть ![image](https://user-images.githubusercontent.com/59570719/218778464-061689f0-197c-49d3-9bd1-3e7fd8be357d.png)

fixed

2023-02-15 18:26 UTC, Denys320 commented
> Зафикси єтот момент, так не должно біть ![image](https://user-images.githubusercontent.com/59570719/218778464-061689f0-197c-49d3-9bd1-3e7fd8be357d.png)

2023-02-15 18:26 UTC, closed without merging

2023-02-15 18:44 UTC, Denys320 commented
> > Зафикси єтот момент, так не должно біть ![image](https://user-images.githubusercontent.com/59570719/218778464-061689f0-197c-49d3-9bd1-3e7fd8be357d.png)


> <img alt="Знімок екрана 2023-02-14 о 16 34 28" width="1440" src="https://user-images.githubusercontent.com/59570719/218780198-f2e516e7-de51-400c-b752-f29df9ddb738.png">


поправил

2023-02-15 18:50 UTC, Denys320 commented on css/styles.css
> +  background: rgba(0, 0, 0, 0.2);
удалил это свойство

2023-02-15 18:50 UTC, Denys320 commented on index.html
>                  alt="watching to the tablet"
поправил

2023-02-18 12:33 UTC, Denys320 commented on portfolio.html
> +              <div class="product-thumb">
поправил)